Fix "undefined reference to `OctoSK6812::pixelBits'" error when compiling with Arduino
I needed to add this line to get the examples to build in my installation.